{{- if .Values.scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "foreman-selfservice.fullname" . }}-scheduler
  labels:
    {{- include "foreman-selfservice.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "foreman-selfservice.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: scheduler
  template:
    metadata:
      labels:
        {{- include "foreman-selfservice.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: scheduler
        {{- with .Values.scheduler.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.scheduler.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "foreman-selfservice.serviceAccountName" . }}
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: {{ .Values.scheduler.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: scheduler
          image: {{ include "foreman-selfservice.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery"]
          args:
            - "-A"
            - "celery_app.celery"
            - "beat"
            - "--loglevel=INFO"
            - "--schedule=/var/run/celery/celerybeat-schedule"
            - "--pidfile=/tmp/celerybeat.pid"
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          envFrom:
            {{- include "foreman-selfservice.commonEnvFrom" . | nindent 12 }}
          env:
            {{- include "foreman-selfservice.commonEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
          volumeMounts:
            {{- include "foreman-selfservice.commonVolumeMounts" . | nindent 12 }}
            - name: celery-state
              mountPath: /var/run/celery
      volumes:
        {{- include "foreman-selfservice.commonVolumes" . | nindent 8 }}
        - name: celery-state
          emptyDir: {}
      {{- with .Values.scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
