{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "foreman-selfservice.fullname" . }}-redis
  labels:
    {{- include "foreman-selfservice.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "foreman-selfservice.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: redis
      protocol: TCP
{{- end }}
