apiVersion: v1
kind: Service
metadata:
  name: {{ include "foreman-selfservice.fullname" . }}
  labels:
    {{- include "foreman-selfservice.labels" . | nindent 4 }}
  {{- with .Values.web.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "foreman-selfservice.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
