"""initial schema"""
from alembic import op
import sqlalchemy as sa
revision="0001_initial"; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("users",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("username",sa.String(160),nullable=False,unique=True),sa.Column("email",sa.String(255)),sa.Column("display_name",sa.String(255)),sa.Column("role",sa.String(32),nullable=False),sa.Column("enabled",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("last_login_at",sa.DateTime(timezone=True)))
    op.create_index("ix_users_username","users",["username"],unique=True); op.create_index("ix_users_email","users",["email"]); op.create_index("ix_users_role","users",["role"])
    op.create_table("auth_identities",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("provider",sa.String(32),nullable=False),sa.Column("subject",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("provider","subject",name="uq_auth_identity_provider_subject")); op.create_index("ix_auth_identities_user_id","auth_identities",["user_id"])
    op.create_table("local_credentials",sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="CASCADE"),primary_key=True),sa.Column("password_hash",sa.String(512),nullable=False),sa.Column("failed_attempts",sa.Integer(),nullable=False),sa.Column("locked_until",sa.DateTime(timezone=True)),sa.Column("password_changed_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("server_groups",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("slug",sa.String(120),nullable=False,unique=True),sa.Column("name",sa.String(160),nullable=False),sa.Column("description",sa.Text()),sa.Column("enabled",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False)); op.create_index("ix_server_groups_slug","server_groups",["slug"],unique=True)
    op.create_table("user_server_groups",sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="CASCADE"),primary_key=True),sa.Column("server_group_id",sa.Integer(),sa.ForeignKey("server_groups.id",ondelete="CASCADE"),primary_key=True))
    op.create_table("approver_server_groups",sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="CASCADE"),primary_key=True),sa.Column("server_group_id",sa.Integer(),sa.ForeignKey("server_groups.id",ondelete="CASCADE"),primary_key=True))
    op.create_table("servers",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("foreman_host_id",sa.Integer(),nullable=False,unique=True),sa.Column("name",sa.String(255),nullable=False,unique=True),sa.Column("ip_address",sa.String(64)),sa.Column("environment",sa.String(120)),sa.Column("group_id",sa.Integer(),sa.ForeignKey("server_groups.id"),nullable=False),sa.Column("enabled",sa.Boolean(),nullable=False),sa.Column("foreman_metadata",sa.JSON()),sa.Column("last_synced_at",sa.DateTime(timezone=True))); op.create_index("ix_servers_foreman_host_id","servers",["foreman_host_id"],unique=True); op.create_index("ix_servers_name","servers",["name"],unique=True); op.create_index("ix_servers_group_id","servers",["group_id"])
    op.create_table("deployment_requests",sa.Column("id",sa.String(36),primary_key=True),sa.Column("request_number",sa.String(32),nullable=False,unique=True),sa.Column("requested_by_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("chiklet_id",sa.String(160),nullable=False),sa.Column("chiklet_name",sa.String(255),nullable=False),sa.Column("chiklet_version",sa.String(64),nullable=False),sa.Column("server_group_id",sa.Integer(),sa.ForeignKey("server_groups.id"),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("justification",sa.Text()),sa.Column("form_data",sa.JSON(),nullable=False),sa.Column("config_snapshot",sa.JSON(),nullable=False),sa.Column("target_snapshot",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("submitted_at",sa.DateTime(timezone=True),nullable=False),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("rejected_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)))
    for c in ["request_number","requested_by_id","chiklet_id","server_group_id","status"]: op.create_index("ix_deployment_requests_"+c,"deployment_requests",[c],unique=(c=="request_number"))
    op.create_table("approvals",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("request_id",sa.String(36),sa.ForeignKey("deployment_requests.id",ondelete="CASCADE"),nullable=False),sa.Column("approver_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("decision",sa.String(16),nullable=False),sa.Column("comment",sa.Text()),sa.Column("decided_at",sa.DateTime(timezone=True),nullable=False)); op.create_index("ix_approvals_request_id","approvals",["request_id"])
    op.create_table("job_executions",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("request_id",sa.String(36),sa.ForeignKey("deployment_requests.id",ondelete="CASCADE"),nullable=False,unique=True),sa.Column("foreman_job_id",sa.String(128)),sa.Column("status",sa.String(32),nullable=False),sa.Column("status_label",sa.String(120)),sa.Column("submitted_at",sa.DateTime(timezone=True)),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("finished_at",sa.DateTime(timezone=True)),sa.Column("last_polled_at",sa.DateTime(timezone=True)),sa.Column("host_results",sa.JSON()),sa.Column("output_excerpt",sa.Text()),sa.Column("error_message",sa.Text())); op.create_index("ix_job_executions_foreman_job_id","job_executions",["foreman_job_id"])
    op.create_table("audit_events",sa.Column("id",sa.BigInteger(),primary_key=True,autoincrement=True),sa.Column("event_id",sa.String(36),nullable=False,unique=True),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("actor_user_id",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("event_type",sa.String(100),nullable=False),sa.Column("entity_type",sa.String(100)),sa.Column("entity_id",sa.String(160)),sa.Column("source_ip",sa.String(64)),sa.Column("user_agent",sa.String(512)),sa.Column("details",sa.JSON()))
    for c in ["occurred_at","actor_user_id","event_type","entity_type","entity_id"]: op.create_index("ix_audit_events_"+c,"audit_events",[c])
def downgrade():
    for t in ["audit_events","job_executions","approvals","deployment_requests","servers","approver_server_groups","user_server_groups","server_groups","local_credentials","auth_identities","users"]: op.drop_table(t)
